### ISSUE TITLE
Please add all token related secrets to .gitignore and REMOVE them from your github.

### ISSUE THREAD

**Issue by DaC00P** [briandhus/Goalie#58]
See public/assets/js/client_secret.json & any others I haven't found yet. 
Deploy these into your Heroku ENV https://devcenter.heroku.com/articles/config-vars

**Comment by DaC00P** [comment]
Also auth.js

**Comment by DaC00P** [comment]
caltest.js

**Comment by lhocke** [comment]
keys removed, leaving issue open for reminder
